name: Scheduled Message

on:
  schedule: 
    - cron: "02 16 * * *"

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem
        run: echo "Bom dia! Essa é uma execução agendada do GitHub Actions."

####