name: GitHub - Secrets do repositório

on:
  workflow_dispatch: #Disparo manual

jobs:
  exemplo-secret:
    runs-on: ubuntu-latest
    steps:
        - name: Usar Secret
          env:
            MINHA_SENHA: ${{ secrets.MINHA_SENHA }}
          run: | 
            echo "Minha Secret é:" $MINHA_SENHA
